'use client';

import Image from 'next/image';
import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion, useScroll, useSpring } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Award, BrainCircuit, BriefcaseBusiness, Check, ChevronRight, Code2, Download, ExternalLink, Github, GraduationCap, Linkedin, Mail, Menu, Moon, Play, Quote, Search, Sparkles, Sun, Terminal, Users, X, MessageCircle, Layers3, Zap } from 'lucide-react';
import { certificates, experience, involvement, projects, skills, socials, type Project } from '../data/content';

const categories = ['All', 'Machine Learning', 'Deep Learning', 'Computer Vision', 'NLP', 'GenAI / RAG', 'Research / ML', 'Applied AI / DSP', 'Expert Systems', 'Backend / Systems'];

export default function Home() {
  const [active, setActive] = useState('All');
  const [selected, setSelected] = useState<Project | null>(null);
  const [menu, setMenu] = useState(false);
  const [light, setLight] = useState(false);
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, { stiffness: 100, damping: 30, restDelta: 0.001 });
  const filtered = useMemo(() => active === 'All' ? projects : projects.filter(p => p.category === active), [active]);

  useEffect(() => {
    const stored = localStorage.getItem('theme');
    const isLight = stored === 'light';
    setLight(isLight);
    document.documentElement.dataset.theme = isLight ? 'light' : 'dark';
  }, []);
  useEffect(() => { document.documentElement.dataset.theme = light ? 'light' : 'dark'; localStorage.setItem('theme', light ? 'light' : 'dark'); }, [light]);
  useEffect(() => { document.body.style.overflow = selected ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [selected]);
  return <main id="top">
    <motion.div className="scroll-progress" style={{ scaleX }} />
    <div className="ambient ambient-a"/><div className="ambient ambient-b"/><div className="ambient ambient-c"/><div className="grid-bg"/><div className="scanline"/>

    <nav className="nav">
      <a className="brand" href="#top" onClick={() => setMenu(false)} aria-label="Abdelrahman Gamal — AI Engineer"><span className="brand-mark"><span>AG</span><i/><b/></span><span className="brand-wordmark"><strong>ABDELRAHMAN</strong><em>GAMAL</em><small>AI ENGINEER</small></span></a>
      <button className="menu-btn" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">{menu ? <X/> : <Menu/>}</button>
      <div className={`nav-links ${menu ? 'open' : ''}`}>{['About','Skills','Projects','Experience','Research','Contact'].map(x => <a key={x} href={`#${x.toLowerCase()}`} onClick={() => setMenu(false)}>{x}</a>)}<a className="nav-cta" href="/assets/resume.pdf" download>CV <Download size={14}/></a><button className="theme-btn" onClick={() => setLight(v => !v)} aria-label="Switch theme"><span className="theme-icon">{light ? <Moon size={14}/> : <Sun size={14}/>}</span><span>{light ? 'Dark' : 'Light'}</span></button></div>
    </nav>

    <section className="hero section-pad">
      <div className="hero-copy">
        <motion.div className="eyebrow" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.1}}><span className="pulse"/> AI / ML ENGINEERING · EGYPT</motion.div>
        <motion.h1 initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.18,duration:.7}}>I engineer AI that <span className="gradient-text">works beyond the notebook.</span></motion.h1>
        <motion.p className="hero-lead" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.3}}>I’m Abdelrahman Gamal, an Artificial Intelligence Engineering student focused on turning data, models and modern AI into practical software across Machine Learning, Computer Vision, NLP and Generative AI.</motion.p>
        <motion.div className="hero-actions" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.42}}><a className="btn primary magnetic" href="#projects">Explore my work <ArrowDownRight size={17}/></a><a className="btn secondary" href="/assets/resume.pdf" download>Download CV <Download size={17}/></a></motion.div>
        <motion.div className="social-row" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.55}}><a href={socials.github} target="_blank" rel="noreferrer"><Github size={16}/> GitHub</a><a href={socials.linkedin} target="_blank" rel="noreferrer"><Linkedin size={16}/> LinkedIn</a><a href={socials.email}><Mail size={16}/> Email</a><span className="social-handle"><MessageCircle size={16}/> {socials.whatsappUsername}</span></motion.div>
        <div className="hero-meta"><span><GraduationCap size={15}/> Expected graduation <b>2028</b></span><span><span className="mini-dot"/> Open to AI/ML opportunities</span></div>
      </div>

      <div className="hero-visual">
        <div className="code-orbit orbit-a"><span>MODEL</span><b>TRAIN()</b><small>loss ↓ · accuracy ↑</small></div><div className="code-orbit orbit-b"><span>PIPELINE</span><b>BUILD → DEPLOY</b><small>data · model · API</small></div>
        <div className="network"><i/><i/><i/><i/><i/><i/><i/><i/><b/><b/><b/><b/></div>
        <div className="three-d-stage" aria-hidden="true"><div className="cube"><span/><span/><span/><span/><span/><span/></div><div className="ring ring-1"/><div className="ring ring-2"/><div className="ring ring-3"/></div>
        <div className="portrait-glow"/><div className="portrait-card"><div className="portrait-frame"><Image src="/assets/profile.jpg" alt="Abdelrahman Gamal" fill priority sizes="(max-width: 900px) 80vw, 430px"/></div><div className="portrait-meta"><div><strong>ABDELRAHMAN GAMAL</strong><span>AI ENGINEERING · 2023—2028</span></div><span className="status-dot"/></div></div>
        <div className="floating-chip chip-one"><BrainCircuit size={15}/> ML / DL</div><div className="floating-chip chip-two"><Code2 size={15}/> Python</div><div className="floating-chip chip-three"><Sparkles size={15}/> GenAI</div>
      </div>
    </section>

    <section className="signal-strip"><div><b>3.7</b><span>GPA / 4.0</span></div><div><b>2028</b><span>Expected graduation</span></div><div><b>ML · CV · NLP</b><span>Core focus</span></div><div><b>RAG · LLMs</b><span>GenAI stack</span></div></section>
    <div className="creative-marquee" aria-hidden="true"><div className="marquee-track"><span>ARTIFICIAL INTELLIGENCE</span><i>✦</i><span>MACHINE LEARNING</span><i>✦</i><span>COMPUTER VISION</span><i>✦</i><span>NLP</span><i>✦</i><span>GENERATIVE AI</span><i>✦</i><span>AI ENGINEERING</span><i>✦</i><span>ARTIFICIAL INTELLIGENCE</span><i>✦</i><span>MACHINE LEARNING</span><i>✦</i><span>COMPUTER VISION</span><i>✦</i><span>NLP</span><i>✦</i><span>GENERATIVE AI</span><i>✦</i></div></div>

    <section id="about" className="section section-pad"><SectionHead kicker="01 / PROFILE" title="Engineer mindset. Practical AI." sub="A short version of how I approach the work."/><div className="about-layout"><motion.div className="about-statement" initial={{opacity:0,x:-24}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.25}}><span className="quote-mark">“</span><p>I’m an Artificial Intelligence Engineering student at New Ismailia National University, building practical AI solutions across <strong>Machine Learning, Deep Learning, Computer Vision, NLP and Generative AI</strong>. I enjoy the complete engineering path — understanding the problem, preparing data, choosing and evaluating models, then turning the result into an application, API or usable workflow. Alongside hands-on projects and intensive technical training, I contribute to AI research and keep pushing toward systems that are useful beyond a notebook.</p><div className="signature"><Terminal size={14}/> build · evaluate · deploy · learn</div></motion.div><div className="about-side"><InfoStat icon={<GraduationCap/>} label="Education" value="AI Engineering" detail="New Ismailia National University"/><InfoStat icon={<Code2/>} label="Engineering style" value="End-to-end" detail="From data to usable systems"/><InfoStat icon={<Sparkles/>} label="Current direction" value="Agentic AI" detail="DEPI · 2026"/></div></div></section>

    <section className="section section-pad usp"><SectionHead kicker="02 / UNIQUE VALUE" title="Technical depth. Practical execution." sub="What I bring to an AI engineering team."/><motion.div className="usp-panel" initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}}><div className="usp-mark"><Zap size={24}/><span>USP</span></div><p>I turn complex AI challenges into practical, reliable, and business-focused solutions across <strong>Machine Learning, Computer Vision, NLP, and Generative AI</strong>—combining strong technical skills with real-world problem solving to deliver models that are accurate, scalable, and ready to create measurable value.</p><div className="usp-footer"><span><Layers3 size={14}/> problem → model → system → impact</span><span>AI ENGINEERING MINDSET</span></div></motion.div><div className="highlight-grid"><Highlight icon={<Check/>} title="End-to-end thinking" text="I move from problem framing and data preparation through model selection, evaluation and usable delivery."/><Highlight icon={<Check/>} title="Evidence over buzzwords" text="Projects and research are presented with technical choices, measurable results and clear engineering context."/><Highlight icon={<Check/>} title="Cross-domain AI" text="A practical stack spanning ML, Deep Learning, Computer Vision, NLP, RAG and Generative AI."/><Highlight icon={<Check/>} title="Builder mentality" text="I care about turning experiments into APIs, dashboards, applications and workflows people can actually use."/></div><div className="quote-card"><Quote size={28}/><div><p>“From models to systems. From ideas to measurable impact.”</p><small>— Abdelrahman Gamal Zayed</small></div></div></section>

    <section id="skills" className="section section-pad"><SectionHead kicker="03 / ENGINEERING STACK" title="Tools I use to turn ideas into systems."/><div className="skill-grid">{Object.entries(skills).map(([group, items], idx)=><motion.div className="skill-card" key={group} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{delay:idx*.06}}><div className="skill-top"><span className="index">0{idx+1}</span><h3>{group}</h3><span className="skill-line"/></div><div className="tag-cloud">{items.map(s=><span key={s}>{s}</span>)}</div></motion.div>)}</div><div className="soft-skills"><span>SOFT SKILLS</span>{['Leadership','Communication','Problem Solving','Adaptability','Teamwork','Time Management'].map(s=><b key={s}>{s}</b>)}</div></section>

    <section id="projects" className="section section-pad"><SectionHead kicker="04 / SELECTED WORK" title="Projects with a reason to exist." sub="Explore by discipline — every card opens a deeper technical view."/><div className="filter-row">{categories.map(c=><button key={c} className={active===c?'active':''} onClick={()=>setActive(c)}>{c}</button>)}</div><motion.div layout className="project-grid">{filtered.map((p,idx)=><ProjectCard key={p.name} p={p} idx={idx} onOpen={()=>setSelected(p)}/>)}</motion.div></section>

    <section id="experience" className="section section-pad"><SectionHead kicker="05 / EXPERIENCE & TRAINING" title="Learning inside real technical environments."/><div className="timeline">{experience.map((e,i)=><motion.div className="timeline-item" key={e.role+e.org} initial={{opacity:0,x:-18}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.15}} transition={{delay:i*.05}}><div className="timeline-marker"/><div className="timeline-date">{e.date}</div><div className="timeline-body"><h3>{e.role}</h3><h4>{e.org}</h4><p>{e.detail}</p></div></motion.div>)}</div></section>

    <section id="research" className="section section-pad research-section"><SectionHead kicker="06 / RESEARCH" title="Where experimentation becomes evidence."/><div className="research-card"><div className="research-image"><Image src="/assets/research-cover.jpg" alt="Solar power forecasting research illustration" fill sizes="(max-width: 900px) 95vw, 50vw"/><span className="research-status">UNDER REVIEW</span></div><div className="research-copy"><span className="project-category">HYBRID FORECASTING · SOLAR ENERGY</span><h3>ELM + Improved Harris Hawks Optimization</h3><p>Co-authored research on solar power forecasting using a hybrid Extreme Learning Machine and Improved Harris Hawks Optimization approach, with benchmarking against CatBoost, XGBoost and Transformer models.</p><div className="metric-grid"><Metric value="0.993" label="R²"/><Metric value="0.167" label="RMSE"/><Metric value="3.75%" label="MAPE"/></div><div className="research-tags">{['ELM','IHO','Forecasting','Model Benchmarking'].map(x=><span key={x}>{x}</span>)}</div></div></div></section>

    <section id="certifications" className="section section-pad"><SectionHead kicker="07 / CREDENTIALS" title="Proof of continuous learning."/><div className="cert-intro"><p>Selected technical training and credentials that support the projects above.</p><div className="cert-count"><Award size={17}/> {certificates.length} credentials</div></div><div className="cert-grid">{certificates.map((c,i)=><motion.a className="cert-card" href={c.file} target="_blank" rel="noreferrer" key={c.title+c.issuer} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.1}} transition={{delay:(i%3)*.04}}><div className="cert-image"><Image src={c.thumb} alt={`${c.title} certificate`} fill sizes="(max-width: 700px) 90vw, 30vw"/></div><div className="cert-info"><div><span>{c.issuer}</span><h3>{c.title}</h3>{c.date&&<small>{c.date}</small>}</div><ExternalLink size={15}/></div></motion.a>)}</div></section>

    <section className="section section-pad involvement"><SectionHead kicker="08 / LEADERSHIP & COMMUNITY" title="AI beyond individual projects."/><div className="involvement-grid">{involvement.map((x,i)=><motion.div className="involvement-card" key={x.role+x.org} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:i*.06}}><div className="involvement-icon">{i===0?<BrainCircuit/>:i===1?<Users/>:<Award/>}</div><span>{x.role}</span><h3>{x.org}</h3><p>{x.detail}</p></motion.div>)}</div></section>

    <section className="section section-pad presence"><SectionHead kicker="09 / PROFESSIONAL PRESENCE" title="See the work in its native spaces."/><div className="presence-grid"><Presence icon={<Github/>} label="CODE / REPOSITORIES" title="GitHub portfolio" text="Projects, experiments and implementation work." href={socials.github}/><Presence icon={<Linkedin/>} label="PROFESSIONAL NETWORK" title="LinkedIn profile" text="Training, milestones, research and professional updates." href={socials.linkedin}/><Presence icon={<Download/>} label="ONE-PAGE OVERVIEW" title="Download CV" text="Education, experience, projects and technical stack." href="/assets/resume.pdf" download/></div></section>

    <section id="contact" className="contact section-pad"><div className="contact-panel"><div><span className="eyebrow">10 / LET’S BUILD</span><h2>Have a problem worth turning into an AI system?</h2><p>For internships, collaborations, research and practical AI projects, I’d be happy to connect.</p><div className="contact-details"><a href={socials.email}><Mail size={15}/>{socials.emailText}</a><a href={socials.phone}><span className="phone-icon">⌕</span>{socials.phoneText}</a><a className="whatsapp-contact" href="https://wa.me/201552519691" target="_blank" rel="noreferrer"><MessageCircle size={15}/> WhatsApp · {socials.whatsappUsername}</a></div></div><div className="contact-actions"><a className="btn primary" href="https://wa.me/201552519691" target="_blank" rel="noreferrer"><MessageCircle size={17}/> Message on WhatsApp <ArrowUpRight size={16}/></a><a className="btn secondary" href={socials.email}>Email me <Mail size={17}/></a></div></div></section>

    <footer><div className="brand"><span className="brand-mark"><span>AG</span><i/><b/></span><span className="brand-wordmark"><strong>ABDELRAHMAN</strong><em>GAMAL</em><small>AI ENGINEER</small></span></div><span>© 2026 Abdelrahman Gamal · Built with Next.js</span><div className="footer-links"><a href={socials.github}>GitHub</a><a href={socials.linkedin}>LinkedIn</a><a href={socials.email}>Email</a><button onClick={()=>setLight(v=>!v)}>{light?<Moon size={14}/>:<Sun size={14}/>} {light?'Dark':'Light'} mode</button></div></footer>

    <AnimatePresence>{selected&&<ProjectModal project={selected} onClose={()=>setSelected(null)}/>}</AnimatePresence>
  </main>;
}

function SectionHead({kicker,title,sub}:{kicker:string;title:string;sub?:string}){return <div className="section-head"><span>{kicker}</span><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>}
function InfoStat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="info-stat"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Metric({value,label}:{value:string;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function Highlight({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="highlight"><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function Presence({icon,label,title,text,href,download}:{icon:React.ReactNode;label:string;title:string;text:string;href:string;download?:boolean}){return <a className="presence-card" href={href} download={download} target={download?undefined:'_blank'} rel={download?undefined:'noreferrer'}><div className="presence-icon">{icon}</div><div><span>{label}</span><h3>{title}</h3><p>{text}</p></div><ArrowUpRight/></a>}
function ProjectCard({p,idx,onOpen}:{p:Project;idx:number;onOpen:()=>void}){return <motion.article layout className="project-card" initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{delay:(idx%3)*.05}} whileHover={{y:-6, rotateX:1, rotateY:-0.4}}><button className="project-media" onClick={onOpen} aria-label={`Open ${p.name}`}>{p.image?<Image src={p.image} alt={`${p.name} project cover`} fill sizes="(max-width: 700px) 95vw, 31vw"/>:<div className="project-placeholder"><span>{p.category}</span><strong>{p.name}</strong><small>CASE STUDY / SYSTEM DESIGN</small></div>}<div className="media-overlay"><span><Play size={14}/> Explore case study</span></div>{p.featured&&<span className="featured-label">FEATURED</span>}</button><div className="project-content"><span className="project-category">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="project-tags">{p.stack.slice(0,4).map(s=><span key={s}>{s}</span>)}</div><div className="project-links"><button onClick={onOpen}>Details <ChevronRight size={13}/></button>{p.demoUrl&&<a className="live-demo-link" href={p.demoUrl} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}><ExternalLink size={14}/> Live demo</a>}{p.github&&<a href={p.github} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}><Github size={14}/> GitHub</a>}</div></div></motion.article>}
function ProjectModal({project,onClose}:{project:Project;onClose:()=>void}){return <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.div className="modal" initial={{opacity:0,y:35,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:25,scale:.98}} onMouseDown={e=>e.stopPropagation}><button className="close" onClick={onClose} aria-label="Close"><X/></button><div className="modal-image">{project.demo?<video src={project.demo} controls playsInline preload="metadata" poster={project.image}/>:project.image?<Image src={project.image} alt="Project visual" fill sizes="90vw"/>:<div className="modal-placeholder"><span>{project.category}</span><strong>{project.name}</strong></div>}</div><div className="modal-body"><span className="project-category">{project.category}</span><h2>{project.name}</h2><p>{project.description}</p><div className="modal-cols"><div><h4>The problem</h4><p>{project.problem}</p></div><div><h4>Technical highlights</h4><ul>{project.highlights.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div></div><div className="modal-stack">{project.stack.map(s=><span key={s}>{s}</span>)}</div><div className="modal-actions">{project.demoUrl&&<a className="btn primary" href={project.demoUrl} target="_blank" rel="noreferrer">Open live demo <ExternalLink size={16}/></a>}{project.github&&<a className={`btn ${project.demoUrl?'secondary':''}`} href={project.github} target="_blank" rel="noreferrer">View on GitHub <Github size={16}/></a>}{project.status&&<span className="status-label">{project.status}</span>}</div></div></motion.div></motion.div>}
